version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    hostname: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Spp!@Cbs44044
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: edris
      MYSQL_PASSWORD: Spp!@Cbs44044
    networks:
      - mysql-network
    volumes:
      - /home/volumns/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql-container
    networks:
      - mysql-network
    ports:
      - "5000:80"

  core-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: erp:core-backend	
    container_name: core-backend
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mominafghanmfi-erp
      DB_USERNAME: root
      DB_PASSWORD: Spp!@Cbs44044
    networks:
      - mysql-network
    ports:
      - "8000:80"
    volumes:
      - /home/volumns/erp:/var/www/storage
    depends_on:
      - mysql

  admin-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: erp:admin-frontend	
    container_name: admin-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - core-backend

networks:
  mysql-network:
    driver: bridge