name: mominafghanmfi-erp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v1.0.3
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}

        script: |
          cd /home/edris/projects/mominafghanmfi-erp/
          git pull origin main

          docker compose up --build -d