name: mominafghanmfi-erp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v1.0.3
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}

        script: |
          cd /home/projects/mominafghanmfi-erp/
          git pull origin main

          docker rm -f mis-frontend
          docker image rm -f mis:frontend
          docker build -t mis:frontend frontend/
          
          docker rm -f core-backend
          docker image rm -f mis:core-backend
          docker build -t mis:core-backend backend/

          docker run -d -p 3000:80 --name mis-frontend --restart=always mis:frontend
          docker run -d -p 8000:80 --name core-backend --restart=always --network mysql-network -v /home/volumes/mominafghanmfi-mis:/var/www/storage mis:core-backend
          docker exec -it core-backend php artisan storage:link
